language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
  - >-
    npm run update-types && git diff --exit-code || (echo -e
    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
    update-types".' && false)
  - >-
    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
    Project is not formatted. Please run "npm run format".' && false)
env:
  global:
    - secure: >-
        dN/Vy15Fci0hyxajn+bmZixrjPu9qllyghw3skHO+NT+W+Sgu7ZngCc7FjC/kNNDRsB5eh4FimGOq37cRrm2NH2j5pyk44UxVILiz0aVFEkiOx/HW0zQzXAcBWj0p62PkRr8ZSf9ixysT7Kv/GqiyEDadzQHcjb8G8VNw3ACnbNWKt51BJzlVtIYw20to1Uc7gL23+7TVZ4I00jAU/OfFkM5EPYsvRz6QQyXljMod4ZLSfkuclD/pFGUCTGkcxSj/YYlKz3P4J1byvkn4WfBjMisQ6BfX7NyLYWlyX18VqgGWJVVi0EgKHtTSzMq3YjR6VDU0wvRkPGjuxg8nHG0lod1d9RIwG+x7StZs4ActJciQVXNQUN+Zrd70b8TA55NBf3gve+YqEC4VNyNHDaA6pXhfNj5PcydrUXSotSpNivXvXyaZzBc0wUha14dQypnroGqAm6tVGMy9volqUUue9JjJTIAaiDmBV+NHV3tiNXzRyht5im9SreeUC3xAW0TQ4kk9+B/SnlHvbmi5TJQE8laQHop9Sl7B0DmFcq1TZ4hnlrZxazfl7C568PyymBPzvKXLRTcnk1kL03z+O0uL9/VtlBComkRqt8aeu2i9ndnD5vFDAfYOM5OkQBYhTMnPLS4iuA6LifpR1BCydIM1lHIMoi5nIMev6Hi6c4E41s=
    - secure: >-
        pR0x9GOLE4bwJoWzQTjBhjPxgBJEvkaLSMcgY+/MrtSPl9yyAKZ+3q3Wp6f3c6XtzyGEk/pZEdzMP+wCPcqWGNfGtUujEDZwWWv3fbl0Lzql2K1Rc2DpvxRC5PsODNc/pR/RJeWLdKTK+/FQbyaVmDQjOLJaLxRj9rhs1hKOegoKIpbSCSYenhNvvHbdgoTRL5ac6yqPx2acAsamCKX9VwHd+kG7ZNHPRJ0H8QUUxxisMiT3RDdsFS9vE5ZI6DAhWWBrBzHxFFIheE7bXb1F7JGJ/t1VuY/AsNnVm0CoB3sj2XI+QvJROuFH9PvyuPVDwv951Pc9aZMYrOAyKGsQst2RMRZtKrlTBQZgDjSZoxR7qH6AedWcmU9ACgJZNzcEHAlhoBfuQ8kMFkS+EREgGynqSFZxxghxF64sLLqT26In7vq/5Hi5a8fSEOWsmFlsL7HziD6XjDKI2nZH3VW1svVmW9YkPVgtY9a7SfMb0uRTaHGDoqag+qOl1Wi1KnJBPdvi+aoLY/oB+BZhUMLU30hg8q4AZ+p6/F8sb/ngdwZpm7ddvcU9D4tmrg64ra57yeyg6b8ShspJ3uXUwFhgxLuN7HltbPLEM6ERch4E+vqyUiAIxAzcrE/q+w4Q9kPzD05wcLILxDsF/dVMXhafOLssyNRSQA5Hb+JaGZEq62c=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
cache:
  directories:
    - node_modules
