language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
  - >-
    npm run update-types && git diff --exit-code || (echo -e
    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
    update-types".' && false)
  - >-
    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
    Project is not formatted. Please run "npm run format".' && false)
env:
  global:
    - secure: >-
        Rg6O66L2oqFmrIGr17RnyD5raJhtkcuGzZzWxNIoWu4Z4EXd43hL5sp7NuRec2+HRoN8lHPthbPbR6BSUT3rK6IC3fXURQ2UdO5JYAomQbxDJfs2U2yumULwMTKWDn1SAFLl9Ya16kmFulx9OQ9/iHBZ5hmbcZkQJQ3+T5q1qEE=
    - secure: >-
        WlHrhLQ3IBKdDyIvz9prPnYLS4hUaklrCkboGnLVM/rwOvI/6pPQq/lsIhEeuOIDOfyK/XdokuYJImy4y0YcSQO9wCmdW2arGhYrxuyvdxo0azkBS19DhOOSOBHN8pINvvxdnB99Eq2x5y+XZjv3uJIvH+3iDAv4Uc7x9AozgcA=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
cache:
  directories:
    - node_modules
