language: node_js
sudo: 'false'
before_script:
  - npm install -g polymer-cli
  - polymer install --variants
  - >-
    npm run update-types && git diff --exit-code || (echo -e
    '\n\033[31mERROR:\033[0m Typings are stale. Please run "npm run
    update-types".' && false)
  - >-
    npm run format && git diff --exit-code || (echo -e '\n\033[31mERROR:\033[0m
    Project is not formatted. Please run "npm run format".' && false)
env:
  global:
    - secure: >-
        qg21qegNt9yboWgMVBJ4XQcfj4dWeYJj840nrT1WLrKO/4TdFpc1//eBLHvT5W9fmShlwCCGBzpRz42Zjn6s3P6ZdONiPoUflBwoAs0yOE6mycQ2XslUdie5o5TSUd3+wGBsqvMbVBMayH+SFOqejNJHzyQbHnxaGkLjay3E4/o=
    - secure: >-
        AkGHsJ0JGgqVBCzgmA/P9wFHikcDQwh8hZ8NmiLjCN4hbuIi7DXREbtG89WAyWxJfhX1zR3RHGLOQqDKHMBseo5pQPMQVafcX45zme5nKB+Pmqou0LeABzZuGIX+x9+gU7a6BVQ4hcfmcwkHiLkjIa9fMju8z9hAzmRS4Wa/3c0=
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
  - xvfb-run polymer test
  - >-
    if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test -s 'default';
    fi
dist: trusty
cache:
  directories:
    - node_modules
